from django.urls import path

from .views import (
    AdminLoginView,
    AdminLogoutView,
    assessment_parameters,
    audit_history,
    dashboard,
    data_source_create,
    data_source_detail,
    data_source_edit,
    data_source_list,
    data_source_transition,
    evacuation_center_create,
    evacuation_center_detail,
    evacuation_center_edit,
    evacuation_center_list,
    evacuation_center_transition,
    guidance_create,
    guidance_edit,
    guidance_list,
    guidance_transition,
    map_data,
    password_help,
    rainfall_reference_detail,
    rainfall_reference_list,
    section,
    settings_view,
)

app_name = "admin_portal"

urlpatterns = [
    path("login/", AdminLoginView.as_view(), name="login"),
    path("logout/", AdminLogoutView.as_view(), name="logout"),
    path("password-help/", password_help, name="password-help"),
    path("", dashboard, name="dashboard"),
    path("map-data/", map_data, name="map-data"),
    path("settings/", settings_view, name="settings"),
    path("assessment-parameters/", assessment_parameters, name="assessment-parameters"),
    path("dss-content/", guidance_list, name="dss-content"),
    path("dss-content/new/", guidance_create, name="guidance-create"),
    path("dss-content/<int:item_id>/edit/", guidance_edit, name="guidance-edit"),
    path(
        "dss-content/<int:item_id>/transition/<slug:action>/",
        guidance_transition,
        name="guidance-transition",
    ),
    path("rainfall-references/", rainfall_reference_list, name="rainfall-references"),
    path(
        "rainfall-references/<int:option_id>/",
        rainfall_reference_detail,
        name="rainfall-reference-detail",
    ),
    path("evacuation-centers/", evacuation_center_list, name="evacuation-centers"),
    path(
        "evacuation-centers/new/",
        evacuation_center_create,
        name="evacuation-center-create",
    ),
    path(
        "evacuation-centers/<int:center_id>/",
        evacuation_center_detail,
        name="evacuation-center-detail",
    ),
    path(
        "evacuation-centers/<int:center_id>/edit/",
        evacuation_center_edit,
        name="evacuation-center-edit",
    ),
    path(
        "evacuation-centers/<int:center_id>/transition/<slug:action>/",
        evacuation_center_transition,
        name="evacuation-center-transition",
    ),
    path("sources-content/", data_source_list, name="sources-content"),
    path("sources-content/new/", data_source_create, name="data-source-create"),
    path(
        "sources-content/<int:source_id>/",
        data_source_detail,
        name="data-source-detail",
    ),
    path(
        "sources-content/<int:source_id>/edit/",
        data_source_edit,
        name="data-source-edit",
    ),
    path(
        "sources-content/<int:source_id>/transition/<slug:action>/",
        data_source_transition,
        name="data-source-transition",
    ),
    path("audit-history/", audit_history, name="audit-history"),
    path("<slug:section_slug>/", section, name="section"),
]
