# Generated by Django 5.2.17 on 2026-09-19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("geography", "0001_initial"),
        ("provenance", "0002_datasource_metadata_and_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvacuationCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=(
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ),
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=(
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ),
                    ),
                ),
                (
                    "contact_information",
                    models.CharField(
                        blank=True,
                        help_text="Add only contact details authorized for this administrative record.",
                        max_length=240,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Enter only a documented and currently verified capacity.",
                        null=True,
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("DEMONSTRATION", "Demonstration data—not official"),
                            ("PENDING_VALIDATION", "Pending validation"),
                            ("APPROVED", "Approved"),
                            ("RESTRICTED", "Restricted"),
                            ("RETIRED", "Retired"),
                        ],
                        default="PENDING_VALIDATION",
                        max_length=30,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In review"),
                            ("VERIFIED", "Verified"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("verified_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("limitations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geographic_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the supported barangay or geographic area when known.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evacuation_centers",
                        to="geography.geographicarea",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evacuation_centers",
                        to="provenance.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "id"),
                "permissions": (
                    ("verify_evacuationcenter", "Can verify evacuation center"),
                    ("deactivate_evacuationcenter", "Can deactivate evacuation center"),
                ),
            },
        )
    ]
