# Generated by Django 5.2.17 on 2026-10-02 07:11

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evacuation", "0002_evacuationcenter_public_id"),
        ("provenance", "0002_datasource_metadata_and_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CenterImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("filename", models.CharField(max_length=180)),
                ("source_revision", models.DateTimeField()),
                ("rows", models.JSONField(default=list)),
                ("shared_limitations", models.TextField(blank=True)),
                ("row_count", models.PositiveIntegerField()),
                ("valid_count", models.PositiveIntegerField()),
                ("invalid_count", models.PositiveIntegerField()),
                ("imported_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_center_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="provenance.datasource"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "row_count",
                                django.db.models.expressions.CombinedExpression(
                                    models.F("valid_count"), "+", models.F("invalid_count")
                                ),
                            )
                        ),
                        name="center_batch_counts_match",
                    )
                ],
            },
        ),
    ]
