# Generated by Django 5.2.17 on 2026-09-21 23:36

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def normalize_existing_identifiers(apps, schema_editor):
    """Fail safely on case collisions, then normalize existing email addresses."""
    User = apps.get_model('accounts', 'User')
    seen = {}
    for user in User.objects.order_by('pk').only('pk', 'email'):
        normalized = user.email.strip().lower()
        if normalized in seen:
            raise RuntimeError(
                'Cannot add case-insensitive email uniqueness: accounts user IDs '
                f"{seen[normalized]} and {user.pk} normalize to the same email."
            )
        seen[normalized] = user.pk
    for user in User.objects.order_by('pk').only('pk', 'email'):
        normalized = user.email.strip().lower()
        if user.email != normalized:
            User.objects.filter(pk=user.pk).update(email=normalized)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('expert', '0002_add_derived_scenario_facts'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google')], max_length=20)),
                ('provider_subject', models.CharField(max_length=255)),
                ('last_verified_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance_source', models.CharField(choices=[('ANDROID', 'Android application'), ('WEB', 'Web application'), ('MIGRATION', 'Legacy migration')], max_length=20)),
                ('application_version', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ('-accepted_at',),
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('short_summary', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TERMS', 'Terms of Use'), ('PRIVACY', 'Privacy Policy')], max_length=20)),
                ('version', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'In review'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('requires_acceptance', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('document_type', '-effective_date', '-id'),
                'permissions': (('review_legaldocumentversion', 'Can review legal document versions'), ('publish_legaldocumentversion', 'Can publish legal document versions')),
            },
        ),
        migrations.CreateModel(
            name='OnboardingAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(default='FloodSense onboarding', max_length=160)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-published_at', '-id'),
                'permissions': (('publish_onboardingversion', 'Can publish onboarding versions'),),
            },
        ),
        migrations.CreateModel(
            name='ResidentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduce_motion', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resident_username',
            field=models.CharField(blank=True, help_text='Normalized resident handle. Existing staff accounts may leave this blank.', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Use 3-30 characters, beginning with a letter, and only letters, numbers, periods, underscores, or hyphens.', regex='^[A-Za-z][A-Za-z0-9_.-]{2,29}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.RunPython(normalize_existing_identifiers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('resident_username'), condition=models.Q(('resident_username__isnull', False)), name='accounts_user_resident_username_ci_unique'),
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailverificationchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalacceptance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legaldocumentversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legal_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legaldocumentversion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_legal_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legaldocumentsection',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.legaldocumentversion'),
        ),
        migrations.AddField(
            model_name='legalacceptance',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='accounts.legaldocumentversion'),
        ),
        migrations.AddField(
            model_name='onboardingacknowledgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_acknowledgements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='onboardingversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('status',), name='one_published_onboarding_version'),
        ),
        migrations.AddField(
            model_name='onboardingacknowledgement',
            name='onboarding_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acknowledgements', to='accounts.onboardingversion'),
        ),
        migrations.AddField(
            model_name='residentpreference',
            name='default_rainfall_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_duration_preferences', to='expert.scenariooption'),
        ),
        migrations.AddField(
            model_name='residentpreference',
            name='default_rainfall_intensity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_intensity_preferences', to='expert.scenariooption'),
        ),
        migrations.AddField(
            model_name='residentpreference',
            name='home_barangay',
            field=models.ForeignKey(blank=True, limit_choices_to={'area_type': 'BARANGAY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_preferences', to='geography.geographicarea'),
        ),
        migrations.AddField(
            model_name='residentpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accountdeletionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('user',), name='one_pending_account_deletion_request'),
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_subject'), name='unique_external_provider_subject'),
        ),
        migrations.AddConstraint(
            model_name='externalidentity',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='one_external_identity_per_provider_per_user'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.UniqueConstraint(fields=('document_type', 'version'), name='unique_legal_document_type_version'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PUBLISHED')), fields=('document_type',), name='one_published_legal_document_per_type'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentsection',
            constraint=models.UniqueConstraint(fields=('document_version', 'section_key'), name='unique_legal_section_key_per_version'),
        ),
        migrations.AddConstraint(
            model_name='legaldocumentsection',
            constraint=models.UniqueConstraint(fields=('document_version', 'display_order'), name='unique_legal_section_order_per_version'),
        ),
        migrations.AddConstraint(
            model_name='legalacceptance',
            constraint=models.UniqueConstraint(fields=('user', 'document_version'), name='unique_legal_acceptance_per_user_version'),
        ),
        migrations.AddConstraint(
            model_name='onboardingacknowledgement',
            constraint=models.UniqueConstraint(fields=('user', 'onboarding_version'), name='unique_onboarding_acknowledgement'),
        ),
    ]
