# Generated by Django 5.2.17 on 2026-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_prototype_legal_and_onboarding_drafts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountdeletionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Scheduled for deletion'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
