# Generated by Django 5.2.17 on 2026-09-10 17:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('provenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('version', models.CharField(max_length=40)),
                ('mode', models.CharField(choices=[('DEMONSTRATION', 'Demonstration'), ('OFFICIAL', 'Approved/official')], max_length=20)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('change_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_sets', to='provenance.datasource')),
            ],
            options={
                'ordering': ('name', 'version'),
            },
        ),
        migrations.CreateModel(
            name='ExpertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('rationale', models.TextField()),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geographic_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expert_rules', to='geography.geographicarea')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_rules', to='provenance.datasource')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='expert.ruleset')),
            ],
            options={
                'ordering': ('ruleset', '-priority', 'code'),
            },
        ),
        migrations.CreateModel(
            name='ScenarioOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INTENSITY', 'Rainfall intensity'), ('DURATION', 'Rainfall duration')], max_length=20)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_options', to='provenance.datasource')),
            ],
            options={
                'ordering': ('category', 'display_order', 'label'),
            },
        ),
        migrations.CreateModel(
            name='ExpertRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('INTENSITY_OPTION', 'Intensity option equals'), ('DURATION_OPTION', 'Duration option equals'), ('AREA_FACT_TEXT', 'Area text fact'), ('AREA_FACT_NUMBER', 'Area numeric fact')], max_length=30)),
                ('operator', models.CharField(choices=[('EQ', 'Equals'), ('GT', 'Greater than'), ('GTE', 'Greater than or equal'), ('LT', 'Less than'), ('LTE', 'Less than or equal')], default='EQ', max_length=5)),
                ('fact_key', models.SlugField(blank=True, max_length=100)),
                ('expected_text', models.CharField(blank=True, max_length=200)),
                ('expected_number', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='expert.expertrule')),
                ('scenario_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_conditions', to='expert.scenariooption')),
            ],
            options={
                'ordering': ('rule', 'display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SusceptibilityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=20, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(unique=True)),
                ('map_color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Use a six-digit hexadecimal color such as #F4C542.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('definition', models.TextField()),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('is_enabled', models.BooleanField(default=False)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='susceptibility_levels', to='provenance.datasource')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.AddField(
            model_name='expertrule',
            name='result_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='expert.susceptibilitylevel'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_ruleset_name_and_version'),
        ),
        migrations.AddConstraint(
            model_name='ruleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('mode',), name='one_active_ruleset_per_mode'),
        ),
        migrations.AddConstraint(
            model_name='scenariooption',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_value__isnull', True), ('maximum_value__isnull', True), ('minimum_value__lte', models.F('maximum_value')), _connector='OR'), name='scenario_minimum_not_above_maximum'),
        ),
        migrations.AddConstraint(
            model_name='expertrule',
            constraint=models.UniqueConstraint(fields=('ruleset', 'code'), name='unique_rule_code_per_ruleset'),
        ),
    ]
