# Generated by Django 5.2.17 on 2026-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariooption',
            name='derived_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Controlled value used by inference, such as a demonstration intensity rank or duration in hours.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expertrulecondition',
            name='condition_type',
            field=models.CharField(choices=[('INTENSITY_OPTION', 'Intensity option equals'), ('DURATION_OPTION', 'Duration option equals'), ('AREA_FACT_TEXT', 'Area text fact'), ('AREA_FACT_NUMBER', 'Area numeric fact'), ('INTENSITY_RANK', 'Rainfall intensity rank'), ('DURATION_HOURS', 'Rainfall duration hours')], max_length=30),
        ),
    ]
