# Generated by Django 5.2.17 on 2026-09-10 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert', '0001_initial'),
        ('provenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('instruction', models.TextField()),
                ('category', models.CharField(choices=[('PREPARE', 'Prepare'), ('MONITOR', 'Monitor official information'), ('PROTECT', 'Protect people and belongings'), ('OFFICIAL_INSTRUCTIONS', 'Follow authorized official instructions')], max_length=30)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guidance_items', to='provenance.datasource')),
                ('susceptibility_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guidance_items', to='expert.susceptibilitylevel')),
            ],
            options={
                'ordering': ('susceptibility_level__display_order', 'display_order', 'id'),
            },
        ),
    ]
