# Generated by Django 5.2.17 on 2026-09-21 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0002_guidance_workflow'),
        ('expert', '0002_add_derived_scenario_facts'),
        ('provenance', '0002_datasource_metadata_and_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSSFlowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('version', models.CharField(max_length=40)),
                ('operating_mode', models.CharField(choices=[('DEMONSTRATION', 'Demonstration'), ('OFFICIAL', 'Approved/official')], max_length=20)),
                ('workflow_status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In review'), ('PUBLISHED', 'Published'), ('RETIRED', 'Retired')], default='DRAFT', max_length=20)),
                ('data_status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dss_flows', to='provenance.datasource')),
                ('susceptibility_levels', models.ManyToManyField(related_name='dss_flows', to='expert.susceptibilitylevel')),
            ],
            options={
                'ordering': ('code', '-effective_date', '-id'),
                'permissions': (('review_dssflowversion', 'Can review structured DSS flow versions'), ('publish_dssflowversion', 'Can publish structured DSS flow versions')),
            },
        ),
        migrations.CreateModel(
            name='DSSOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('instruction', models.TextField()),
                ('category', models.CharField(choices=[('PREPARE', 'Prepare'), ('MONITOR', 'Monitor official information'), ('PROTECT', 'Protect people and belongings'), ('OFFICIAL_INSTRUCTIONS', 'Follow authorized official instructions')], max_length=40)),
                ('warning', models.TextField(default='Preparedness guidance is not an evacuation order. Follow official authorities and emergency services.')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='dss.dssflowversion')),
                ('guidance_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structured_outcomes', to='dss.guidanceitem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dss_outcomes', to='provenance.datasource')),
            ],
            options={
                'ordering': ('flow', 'code'),
            },
        ),
        migrations.CreateModel(
            name='DSSQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('prompt', models.CharField(max_length=300)),
                ('explanatory_text', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single choice')], default='SINGLE_CHOICE', max_length=30)),
                ('is_start', models.BooleanField(default=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dss.dssflowversion')),
            ],
            options={
                'ordering': ('flow', 'display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='DSSOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=200)),
                ('supporting_text', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_options', to='dss.dssoutcome')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_options', to='dss.dssquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dss.dssquestion')),
            ],
            options={
                'ordering': ('question', 'display_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='dssflowversion',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='unique_dss_flow_code_version'),
        ),
        migrations.AddConstraint(
            model_name='dssflowversion',
            constraint=models.UniqueConstraint(condition=models.Q(('workflow_status', 'PUBLISHED')), fields=('code', 'operating_mode'), name='one_published_dss_flow_per_code_mode'),
        ),
        migrations.AddConstraint(
            model_name='dssoutcome',
            constraint=models.UniqueConstraint(fields=('flow', 'code'), name='unique_dss_outcome_code_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='dssquestion',
            constraint=models.UniqueConstraint(fields=('flow', 'code'), name='unique_dss_question_code_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='dssquestion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_start', True)), fields=('flow',), name='one_dss_start_question_per_flow'),
        ),
        migrations.AddConstraint(
            model_name='dssoption',
            constraint=models.UniqueConstraint(fields=('question', 'code'), name='unique_dss_option_code_per_question'),
        ),
        migrations.AddConstraint(
            model_name='dssoption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('next_question__isnull', False), ('outcome__isnull', True)), models.Q(('next_question__isnull', True), ('outcome__isnull', False)), _connector='OR'), name='dss_option_has_exactly_one_destination'),
        ),
    ]
