# Generated by Django 5.2.17 on 2026-10-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0003_dssflowversion_dssoutcome_dssquestion_dssoption_and_more'),
        ('provenance', '0002_datasource_metadata_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dssflowversion',
            name='attribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dssflowversion',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dssflowversion',
            name='limitations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dssflowversion',
            name='reviewed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dssflowversion',
            name='source_locator',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='dssoutcome',
            name='guidance_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='structured_outcomes', to='dss.guidanceitem'),
        ),
        migrations.CreateModel(
            name='DSSContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('BEFORE', 'Before a flood'), ('DURING', 'During a flood — educational reference'), ('AFTER', 'After a flood — educational reference'), ('ALWAYS', 'General preparedness')], default='BEFORE', max_length=10)),
                ('content_type', models.CharField(choices=[('HOUSEHOLD_ACTION', 'Household action'), ('SCENARIO_EXPLANATION', 'Scenario explanation'), ('OFFICIAL_CHANNEL', 'Official information channel'), ('MONITORING_REFERENCE', 'Monitoring reference'), ('AUTHORITY_ACTIVITY', 'Authority activity'), ('RISK_REFERENCE', 'Risk-knowledge reference')], max_length=30)),
                ('audience', models.CharField(choices=[('RESIDENT', 'Resident'), ('HOUSEHOLD_SUPPORT', 'Household support'), ('PUBLIC_REFERENCE', 'Public educational reference'), ('STAFF_ONLY', 'Staff only — not public guidance')], default='RESIDENT', max_length=30)),
                ('reference_stage', models.CharField(blank=True, choices=[('GREEN', 'Green board reference — no susceptibility mapping'), ('YELLOW', 'Yellow board reference — no susceptibility mapping'), ('ORANGE', 'Orange board reference — no susceptibility mapping'), ('RED', 'Red board reference — no susceptibility mapping')], max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('data_status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='PENDING_VALIDATION', max_length=30)),
                ('source_locator', models.CharField(blank=True, max_length=300)),
                ('attribution', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('public_url', models.URLField(blank=True)),
                ('url_verified_on', models.DateField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='dss.dssflowversion')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='dss.dssoutcome')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dss_blocks', to='provenance.datasource')),
            ],
            options={
                'ordering': ('display_order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('reference_stage', ''), ('audience', 'STAFF_ONLY'), _connector='OR'), name='dss_board_stage_staff_only')],
            },
        ),
    ]
