# Generated by Django 5.2.17 on 2026-09-10 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('source_type', models.CharField(choices=[('DEMONSTRATION', 'Demonstration/synthetic'), ('AGENCY_DATASET', 'Government/agency dataset'), ('INTERVIEW', 'Interview or expert consultation'), ('PUBLICATION', 'Publication or official guidance'), ('OTHER', 'Other')], max_length=30)),
                ('coverage_description', models.TextField(blank=True)),
                ('record_period_start', models.DateField(blank=True, null=True)),
                ('record_period_end', models.DateField(blank=True, null=True)),
                ('received_or_created_on', models.DateField(blank=True, null=True)),
                ('permitted_use', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('is_publicly_releasable', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
    ]
