# Generated by Django 5.2.17 on 2026-09-19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("provenance", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="citation_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="datasource",
            name="custodian",
            field=models.CharField(
                blank=True,
                help_text="Office or role responsible for maintaining this source.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="limitations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="datasource",
            name="processing_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="datasource",
            name="version",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterModelOptions(
            name="datasource",
            options={
                "ordering": ("name", "id"),
                "permissions": (
                    ("approve_datasource", "Can approve data source metadata"),
                    ("publish_datasource", "Can publish data source metadata"),
                    ("restrict_datasource", "Can restrict data source metadata"),
                ),
            },
        ),
    ]
