# Generated by Django 5.2.17 on 2026-09-10 17:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('area_type', models.CharField(choices=[('DEMO_ZONE', 'Demonstration zone'), ('CITY', 'City'), ('BARANGAY', 'Barangay'), ('OTHER', 'Other')], max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geographic_areas', to='provenance.datasource')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AreaFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_key', models.SlugField(max_length=100)),
                ('text_value', models.CharField(blank=True, max_length=200)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='DEMONSTRATION', max_length=30)),
                ('effective_on', models.DateField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_facts', to='provenance.datasource')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='geography.geographicarea')),
            ],
            options={
                'ordering': ('area__name', 'fact_key', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('text_value', ''), ('numeric_value__isnull', False)), models.Q(models.Q(('text_value', ''), _negated=True), ('numeric_value__isnull', True)), _connector='OR'), name='area_fact_has_exactly_one_value')],
            },
        ),
    ]
