# Generated by Django 5.2.17 on 2026-09-23 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('provenance', '0002_datasource_metadata_and_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodSusceptibilityDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('source_field', models.CharField(default='FloodSusc', max_length=80)),
                ('source_accessed_on', models.DateField()),
                ('generated_at', models.DateTimeField()),
                ('aggregation_method', models.CharField(choices=[('DOMINANT_MAPPED_AREA', 'Largest mapped LF/MF/HF/VHF area share')], default='DOMINANT_MAPPED_AREA', max_length=40)),
                ('summary_sha256', models.CharField(max_length=64)),
                ('validation_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('DEMONSTRATION', 'Demonstration data—not official'), ('PENDING_VALIDATION', 'Pending validation'), ('APPROVED', 'Approved'), ('RESTRICTED', 'Restricted'), ('RETIRED', 'Retired')], default='PENDING_VALIDATION', max_length=30)),
                ('is_active_for_consultation', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flood_susceptibility_datasets', to='provenance.datasource')),
            ],
            options={
                'ordering': ('-generated_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BarangaySusceptibilitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_area_sqm', models.DecimalField(decimal_places=3, max_digits=16)),
                ('lf_area_sqm', models.DecimalField(decimal_places=3, max_digits=16)),
                ('lf_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mf_area_sqm', models.DecimalField(decimal_places=3, max_digits=16)),
                ('mf_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('hf_area_sqm', models.DecimalField(decimal_places=3, max_digits=16)),
                ('hf_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('vhf_area_sqm', models.DecimalField(decimal_places=3, max_digits=16)),
                ('vhf_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('conflict_area_sqm', models.DecimalField(decimal_places=3, max_digits=16)),
                ('conflict_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('unmapped_area_sqm', models.DecimalField(decimal_places=3, max_digits=16)),
                ('unmapped_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('partition_percent_total', models.DecimalField(decimal_places=4, max_digits=7)),
                ('dominant_class', models.CharField(blank=True, choices=[('LF', 'Low'), ('MF', 'Moderate'), ('HF', 'High'), ('VHF', 'Very High')], max_length=4, null=True)),
                ('dominant_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('baseline_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='susceptibility_summaries', to='geography.geographicarea')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangay_summaries', to='geography.floodsusceptibilitydataset')),
            ],
            options={
                'ordering': ('area__name', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='floodsusceptibilitydataset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active_for_consultation', True)), fields=('is_active_for_consultation',), name='one_active_consultation_susceptibility_dataset'),
        ),
        migrations.AddConstraint(
            model_name='barangaysusceptibilitysummary',
            constraint=models.UniqueConstraint(fields=('dataset', 'area'), name='unique_barangay_summary_per_dataset'),
        ),
    ]
